name: Feature

on:
  push:
    branches:
      - 'feature/**'
permissions:
  pull-requests: write

jobs:
  terraform-format:
    name: Check Terraform Format
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Terraform Format
        run: terraform fmt -check

        

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init


      - name: Terraform Plan
        run: terraform plan -parallelism=40
  

  createPullRequest:
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pr_title: "Merge Feature para Main"
          pr_body: "Pull request automático para main."
          pr_label: "automated-pr"
          pr_draft: true
          base: "main"
          head: "${{ github.ref }}"

  database-migration:
    name: Database Migration
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Database Migrations
        run: |
          psql -h db-fiap-burger-svc -U cG9zdGdyZXM= -d postgres -a -f database/migrations/01_create_tables.sql
        env:
          PGPASSWORD: 'MTIzNDU2'
